apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: http-monitor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-monitor
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
