apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: http-monitor-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: http-monitor
  endpoints:
  - port: 8000
    interval: 15s
