apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  labels:
    app: go-app
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app-container
        image: {{ .Values.gload.image.repository }}:{{ .Values.gload.image.tag}}
        ports:
        - containerPort: { { .Values.gload.container.port } }
